// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_tAR2bU6VHL05AeIxCMUmMkSt04aOiAE',
    appId: '1:171630190575:web:3d44af6eabaa3badefe01a',
    messagingSenderId: '171630190575',
    projectId: 'megawatt-16853',
    authDomain: 'megawatt-16853.firebaseapp.com',
    storageBucket: 'megawatt-16853.firebasestorage.app',
    measurementId: 'G-184EP6GNYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKzK6Z8OPgdSaACiWmfnzUxjiCVDxc2qo',
    appId: '1:171630190575:android:1995da0a62d815e5efe01a',
    messagingSenderId: '171630190575',
    projectId: 'megawatt-16853',
    storageBucket: 'megawatt-16853.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqbqF51agr0ij8cAJWNBX11AZfx0brVVw',
    appId: '1:171630190575:ios:90d929407abfb8a0efe01a',
    messagingSenderId: '171630190575',
    projectId: 'megawatt-16853',
    storageBucket: 'megawatt-16853.firebasestorage.app',
    iosBundleId: 'com.example.megawatt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqbqF51agr0ij8cAJWNBX11AZfx0brVVw',
    appId: '1:171630190575:ios:90d929407abfb8a0efe01a',
    messagingSenderId: '171630190575',
    projectId: 'megawatt-16853',
    storageBucket: 'megawatt-16853.firebasestorage.app',
    iosBundleId: 'com.example.megawatt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_tAR2bU6VHL05AeIxCMUmMkSt04aOiAE',
    appId: '1:171630190575:web:db6a1d770a1dfd27efe01a',
    messagingSenderId: '171630190575',
    projectId: 'megawatt-16853',
    authDomain: 'megawatt-16853.firebaseapp.com',
    storageBucket: 'megawatt-16853.firebasestorage.app',
    measurementId: 'G-MJSD2F34B7',
  );
}
